### ISSUE TITLE
[Suggestion] Add a `jumping` entity condition type

### ISSUE THREAD

**Issue by Reniel80** [apace100/apoli#185]
This `Jumping` condition type can be used to consume energy from a player energy system or create moves for a parkour system.

**Comment by eggohito** [comment]
I'd argue adding a `key_pressed` entity condition type (like [Apugli's `key_pressed` entity condition type](https://apugli.readthedocs.io/en/latest/types/entity_condition_types/key_pressed)) instead of a `jumping` entity condition type since with that, it'll be more than just for detecting whether a player is pressing/holding the jump keybind **and** was on the ground

There is also not really an indicator for whether a player is jumping apart from what I've described (as far as I know), so it'll be better to have a general solution instead of a specific one (which will likely be niche)

**Comment by ChrysanthCow** [comment]
> I'd argue adding a `key_pressed` entity condition type (like [Apugli's `key_pressed` entity condition type](https://apugli.readthedocs.io/en/latest/types/entity_condition_types/key_pressed)) instead of a `jumping` entity condition type since with that, it'll be more than just for detecting whether a player is pressing/holding the jump keybind **and** was on the ground
> 
> There is also not really an indicator for whether a player is jumping apart from what I've described (as far as I know), so it'll be better to have a general solution instead of a specific one (which will likely be niche)

Sooo, shall I PR Key Press optimisations as well as that condition? (We need to not be sending packets as often for this)

**Comment by Reniel80** [comment]
Indeed.. a key_pressed entity condition type is perfect.

**Comment by eggohito** [comment]
> > I'd argue adding a `key_pressed` entity condition type (like [Apugli's `key_pressed` entity condition type](https://apugli.readthedocs.io/en/latest/types/entity_condition_types/key_pressed)) instead of a `jumping` entity condition type since with that, it'll be more than just for detecting whether a player is pressing/holding the jump keybind **and** was on the ground
> > There is also not really an indicator for whether a player is jumping apart from what I've described (as far as I know), so it'll be better to have a general solution instead of a specific one (which will likely be niche)
> 
> Sooo, shall I PR Key Press optimisations as well as that condition? (We need to not be sending packets as often for this)

That would be awesome. No pressure though, especially since the packet issue is a bit tough to figure out (which is also why I haven't added eggolib's `in_screen` and `perspective` entity condition types yet)
