### ISSUE TITLE
Legacy Damage Sources are not correctly compared with `apoli:name` damage type condition.

### ISSUE THREAD

**Issue by ChrysanthCow** [apace100/apoli#207]
Please refer to:
https://github.com/EdwinMindcraft/origins-architectury/issues/422

**Comment by ChrysanthCow** [comment]
You may want to migrate this issue over to Apoli, I think it'd be easier tracked over there.

**Comment by eggohito** [comment]
I think there are three ways of fixing this: we can correct the logic for querying for the best damage type by also comparing the message ID of the damage type to the name defined in the `DamageSourceDescription` instance, account for the `NameMutableDamageSource` duck interface in the `name` damage condition type, or both

I've been actually aware of the first part of the issue for a while now, just wasn't sure whether that would encourage users to keep using the `damage_source`/`source` fields, which have been deprecated :thinking:

**Comment by ChrysanthCow** [comment]
That's fair. I'd probably say to do the first one for the sake of legacy datapacks, and id alao suggest making them always return `false` for the type condition.

I doubt this would be encouragement either, as datapack damage types are far more powerful and are more suited to datapacks.

 Its more on the individual if they're a retrograde who sticks to old methods.

**Comment by eggohito** [comment]
> id alao suggest making them always return `false` for the type condition.

Oh, I don't think there's actually a need for this since I've recently added validation to tag/registry key data types in Calio. So, if a user were to reference a damage type that does not exist (e.g: `inWall`, instead of `in_wall`), it would output an error and prevent the power from being registered instead of potentially crashing the game

> Its more on the individual if they're a retrograde who sticks to old methods.

Oh yeah, that was my concern since we ought to break backwards compatibility at some point, but you're right on the custom damage types part

**Comment by ChrysanthCow** [comment]
Alright

**Comment by ChrysanthCow** [comment]
Also in regards for the type condition, the reason why I suggested it was because they will return true for the resolved damage type that's used as the basis for the legacy damage source description
