### ISSUE TITLE
[Performance] LivingEntity baseTick mixin does unnecessary work on non-player entities

### ISSUE THREAD

**Issue by jupjohn** [apace100/apoli#216]
Was digging through a profile of a server running Origins & some other origin-related mods, and noticed that there was an apoli function taking up a chunk of every living entity tick. The function is `InventoryUtil.forEachStack(Entity, Consumer<ItemStack>)` which looks like it's meant to be for tracking powerup items held by players - not other non-player entities. 
 
![image](https://github.com/apace100/apoli/assets/4962764/304056ad-b528-4d50-b549-82252d15af02)
![image](https://github.com/apace100/apoli/assets/4962764/c34bd175-e696-4ac5-a435-baf03546bc28)

Is there a good reason to have this taking up precious tick time on all entities that I'm missing?
I've already patched it out on my fork for a specific older version of Origins, but if I can confirm there's no reason to have that running on all mobs I'll submit the patch here too.

**Comment by jupjohn** [comment]
My patch for reference: https://github.com/jupjohn/apoli-greasy-patch/commit/dab7815d9704e37db0b77bf60e1c6fa61a48af28

**Comment by eggohito** [comment]
As shown in the flame graph, this was due to the item slots that are used for operating on the item stacks within the said slots being duplicated via `com.google.common.collect.Sets#newHashSet()`. This has long been optimized in https://github.com/apace100/apoli/commit/d391b2bec9929d0d2dddfb6e2e9a39c00e6ef4d3 (from Apoli v2.10.0), but hasn't been backported yet

**Comment by eggohito** [comment]
The reference of the entity is cached to the item stacks in order to be able to reference the said entity where an entity is not used as a parameter (e.g: when generating enchantments, in the case for the `modify_enchantment_level` power type). And since living entities (mobs, players, armor stands, etc.) can have powers, it has to process non-player entities too

**Comment by jupjohn** [comment]
Gotcha. My understanding of the mod is limited so thanks for explaining the behaviour. I'll look at back porting that fix to the version I'm using, and see how it goes.

Closing due to non-issue.
