### ISSUE TITLE
Sleeping in a bed as a Fae from Collection of Singiro crashes the server

### ISSUE THREAD

**Issue by numerobis21** [apace100/apoli#64]
I have a server with Collection of Singiro (Origins) installed, and one of my players crashed the server by sleeping (it wasn't his first time sleeping though), and each time he tries to connect to the server, the server crashes again

From my limited understanding, the last lines of this crash report refer to the problem

[latest.log](https://github.com/apace100/apoli/files/9376567/latest.log)
.

**Comment by eggohito** [comment]
It seems that you're using the **unofficial** Forge port of Origins, Calio and Apoli. This isn't really the appropriate place to report the issue since Apace is not the maintainer of the **unofficial** Forge ports. [You can report the 'argument type' issue here](https://github.com/EdwinMindcraft/origins-architectury)
